#!/usr/bin/env python3
"""Extract foreground sprite cutouts from the background by HSV mask."""
from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
SCENE = ROOT / 'public' / 'kotodama_bg.png'
OUT_DIR = ROOT / 'public' / 'cutouts'
OUT_DIR.mkdir(parents=True, exist_ok=True)
META = ROOT / 'tools' / 'scene-bbox' / 'cutouts.json'


def crop(bgr, x, y, w, h):
    return bgr[y:y + h, x:x + w]


def mask_red(hsv):
    m1 = cv2.inRange(hsv, (0, 70, 60), (12, 255, 255))
    m2 = cv2.inRange(hsv, (165, 70, 60), (180, 255, 255))
    return m1 | m2


def mask_dark_roof(hsv, top_only_ratio=0.45):
    m = cv2.inRange(hsv, (90, 40, 0), (140, 220, 55))
    cut = int(hsv.shape[0] * top_only_ratio)
    m[cut:, :] = 0
    return m


def mask_torii_pole(hsv):
    # 鸟居粉色高光：H 围绕红、亮度高
    return cv2.inRange(hsv, (0, 30, 140), (15, 255, 255))


def clean(mask, close=2, open_=1):
    kernel = np.ones((3, 3), np.uint8)
    out = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=close)
    out = cv2.morphologyEx(out, cv2.MORPH_OPEN, kernel, iterations=open_)
    return out


def fill_holes(mask, max_hole=600):
    inv = cv2.bitwise_not(mask)
    n, labels, stats, _ = cv2.connectedComponentsWithStats(inv, connectivity=4)
    out = mask.copy()
    h, w = mask.shape
    for i in range(1, n):
        x = stats[i, cv2.CC_STAT_LEFT]
        y = stats[i, cv2.CC_STAT_TOP]
        ww = stats[i, cv2.CC_STAT_WIDTH]
        hh = stats[i, cv2.CC_STAT_HEIGHT]
        if x == 0 or y == 0 or x + ww == w or y + hh == h:
            continue
        area = stats[i, cv2.CC_STAT_AREA]
        if area < max_hole:
            out[labels == i] = 255
    return out


def keep_largest(mask, min_area=4000):
    n, labels, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)
    if n <= 1:
        return mask
    out = np.zeros_like(mask)
    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out[labels == largest_idx] = 255
    for i in range(1, n):
        if i == largest_idx:
            continue
        if stats[i, cv2.CC_STAT_AREA] < min_area:
            continue
        # 连接到主体且面积可观的块也保留（鸟居横梁分块时兜底）
        ys, xs = np.where(labels == i)
        if len(xs) == 0:
            continue
        cx = stats[i, cv2.CC_STAT_LEFT] + stats[i, cv2.CC_STAT_WIDTH] // 2
        cy = stats[i, cv2.CC_STAT_TOP] + stats[i, cv2.CC_STAT_HEIGHT] // 2
        main_cx = stats[largest_idx, cv2.CC_STAT_LEFT] + stats[largest_idx, cv2.CC_STAT_WIDTH] // 2
        main_cy = stats[largest_idx, cv2.CC_STAT_TOP] + stats[largest_idx, cv2.CC_STAT_HEIGHT] // 2
        # 仅保留落在主体中心 ±220 像素的块
        if abs(cx - main_cx) <= 220 and abs(cy - main_cy) <= 320:
            out[labels == i] = 255
    return out


def to_bgra(region, mask):
    bgra = cv2.cvtColor(region, cv2.COLOR_BGR2BGRA)
    bgra[:, :, 3] = mask
    return bgra


def trim_to_alpha(bgra):
    alpha = bgra[:, :, 3]
    ys, xs = np.where(alpha > 0)
    if len(xs) == 0:
        return bgra, (0, 0, bgra.shape[1], bgra.shape[0])
    x0, x1 = xs.min(), xs.max()
    y0, y1 = ys.min(), ys.max()
    cropped = bgra[y0:y1 + 1, x0:x1 + 1]
    return cropped, (int(x0), int(y0), int(x1 - x0 + 1), int(y1 - y0 + 1))


def cutout_torii(bgr):
    x, y, w, h = 2891, 69, 611, 643
    region = crop(bgr, x, y, w, h)
    hsv = cv2.cvtColor(region, cv2.COLOR_BGR2HSV)
    mask = mask_red(hsv) | mask_dark_roof(hsv) | mask_torii_pole(hsv)
    mask = clean(mask, close=3, open_=1)
    mask = keep_largest(mask, min_area=4000)
    mask = fill_holes(mask, max_hole=600)
    bgra = to_bgra(region, mask)
    trimmed, (dx, dy, tw, th) = trim_to_alpha(bgra)
    return trimmed, {'sceneX': x + dx, 'sceneY': y + dy, 'w': tw, 'h': th}


def main():
    bgr = cv2.imread(str(SCENE), cv2.IMREAD_COLOR)
    meta = {'image': '/kotodama_bg.png', 'cutouts': []}

    torii, info = cutout_torii(bgr)
    cv2.imwrite(str(OUT_DIR / 'upper_right_torii.png'), torii)
    meta['cutouts'].append({
        'id': 'upper_right_torii',
        'src': '/cutouts/upper_right_torii.png',
        **info,
        'anchorY': info['sceneY'] + info['h'] - 8,
    })

    import json
    META.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
    ts = (
        "// auto-generated by tools/scene-bbox/cutouts.py - do not edit\n"
        "export type SceneCutout = {\n"
        "  id: string\n"
        "  src: string\n"
        "  sceneX: number\n"
        "  sceneY: number\n"
        "  w: number\n"
        "  h: number\n"
        "  anchorY: number\n"
        "}\n\n"
        "export const SCENE_CUTOUTS: SceneCutout[] = "
        + json.dumps(meta['cutouts'], ensure_ascii=False, indent=2)
        + "\n"
    )
    (ROOT / 'src' / 'data' / 'cutouts.ts').write_text(ts)
    for c in meta['cutouts']:
        print(f"saved {c['src']}  scene=({c['sceneX']},{c['sceneY']}) size={c['w']}x{c['h']} anchorY={c['anchorY']}")


if __name__ == '__main__':
    main()
