#!/usr/bin/env python3
"""把 public/scene/overlaps.json 的每条 polygon 转成"骨架遮挡 cutout"。

思路：
- 取背景图被 polygon 圈住的子区域
- 跑 Canny 边缘检测 + 膨胀 → 得到稀疏 mask
- mask=1 的像素保留原色，其它 alpha=0
- 输出 PNG 到 public/cutouts/overlap_NN.png
- 写元数据 src/data/overlapCutouts.ts

效果：玩家走过 overlap 区域时，只被物件的"线条/木条"挡住，缝隙处完全可见。
"""
from __future__ import annotations

import json
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
SCENE_IMG = ROOT / 'public' / 'kotodama_bg.png'
OVERLAPS_JSON = ROOT / 'public' / 'scene' / 'overlaps.json'
OUT_DIR = ROOT / 'public' / 'cutouts'
OUT_DIR.mkdir(parents=True, exist_ok=True)
META_TS = ROOT / 'src' / 'data' / 'overlapCutouts.ts'

# 边缘检测参数
CANNY_LO = 60
CANNY_HI = 180
DILATE_ITER = 1
DILATE_KERNEL = 3

# 仅右下角的物件（绘马架等带镂空结构）走边缘骨架，其他 polygon 走 SVG clipPath 实心
# 实心遮挡 = 背景被该 polygon 区域整片重画到玩家上方，物件视觉更立体
SKELETON_AREA = (2900, 1400, 940, 760)  # x, y, w, h


def in_skeleton_area(cx: float, cy: float) -> bool:
    if SKELETON_AREA is None:
        return True
    x, y, w, h = SKELETON_AREA
    return x <= cx <= x + w and y <= cy <= y + h


def load_overlaps():
    if not OVERLAPS_JSON.exists():
        print(f'no overlap file: {OVERLAPS_JSON}')
        return []
    data = json.loads(OVERLAPS_JSON.read_text(encoding='utf-8'))
    if isinstance(data, dict):
        return data.get('overlap') or data.get('strokes') or []
    if isinstance(data, list):
        return data
    return []


def polygon_bbox(points):
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x0, y0 = max(0, min(xs)), max(0, min(ys))
    x1, y1 = max(xs), max(ys)
    return int(x0), int(y0), int(x1), int(y1)


def process_polygon(bgr, points, index):
    h_img, w_img = bgr.shape[:2]
    x0, y0, x1, y1 = polygon_bbox(points)
    x1 = min(w_img, x1 + 1)
    y1 = min(h_img, y1 + 1)
    if x1 <= x0 or y1 <= y0:
        return None
    region = bgr[y0:y1, x0:x1]
    H, W = region.shape[:2]

    # polygon mask（局部坐标）
    local_pts = np.array([[p[0] - x0, p[1] - y0] for p in points], dtype=np.int32)
    poly_mask = np.zeros((H, W), dtype=np.uint8)
    cv2.fillPoly(poly_mask, [local_pts], 255)

    # 边缘
    gray = cv2.cvtColor(region, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (3, 3), 0)
    edges = cv2.Canny(blurred, CANNY_LO, CANNY_HI, L2gradient=True)

    # 膨胀让线条粗一点（让物件 silhouette 看起来连贯）
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (DILATE_KERNEL, DILATE_KERNEL))
    edges = cv2.dilate(edges, kernel, iterations=DILATE_ITER)

    # 只保留 polygon 内的边缘
    alpha = cv2.bitwise_and(edges, edges, mask=poly_mask)

    if alpha.max() == 0:
        return None

    bgra = cv2.cvtColor(region, cv2.COLOR_BGR2BGRA)
    bgra[:, :, 3] = alpha

    out_path = OUT_DIR / f'overlap_{index:02d}.png'
    cv2.imwrite(str(out_path), bgra)

    return {
        'src': f'/cutouts/overlap_{index:02d}.png',
        'sceneX': x0,
        'sceneY': y0,
        'w': W,
        'h': H,
    }


def main():
    bgr = cv2.imread(str(SCENE_IMG), cv2.IMREAD_COLOR)
    if bgr is None:
        raise SystemExit(f'cannot read {SCENE_IMG}')

    overlaps = load_overlaps()
    print(f'载入 overlap polygon：{len(overlaps)} 条')
    print(f'骨架区域：{SKELETON_AREA}')

    # 清理旧 overlap_*.png
    for old in OUT_DIR.glob('overlap_*.png'):
        old.unlink()

    skeleton_metas = []
    solid_metas = []
    for i, poly in enumerate(overlaps):
        if isinstance(poly, dict):
            points = poly.get('points', [])
        else:
            points = poly
        if not isinstance(points, list) or len(points) < 3:
            continue

        x0, y0, x1, y1 = polygon_bbox(points)
        cx = (x0 + x1) / 2
        cy = (y0 + y1) / 2

        if in_skeleton_area(cx, cy):
            info = process_polygon(bgr, points, i)
            if info:
                skeleton_metas.append({'id': f'overlap_{i:02d}', **info})
                print(f'  [骨架] overlap_{i:02d}: {info["w"]}x{info["h"]} at ({info["sceneX"]},{info["sceneY"]})')
        else:
            solid_metas.append({
                'id': f'overlap_{i:02d}',
                'points': [[int(p[0]), int(p[1])] for p in points],
            })

    print(f'  [实心] {len(solid_metas)} 条沿用 SVG clipPath 整片遮挡')

    ts = (
        '// auto-generated by tools/scene-bbox/overlap_to_cutouts.py - do not edit\n'
        'export type SkeletonOverlap = {\n'
        '  id: string\n'
        '  src: string\n'
        '  sceneX: number\n'
        '  sceneY: number\n'
        '  w: number\n'
        '  h: number\n'
        '}\n\n'
        'export type SolidOverlap = {\n'
        '  id: string\n'
        '  points: [number, number][]\n'
        '}\n\n'
        'export const SKELETON_OVERLAPS: SkeletonOverlap[] = '
        + json.dumps(skeleton_metas, ensure_ascii=False, indent=2)
        + '\n\n'
        'export const SOLID_OVERLAPS: SolidOverlap[] = '
        + json.dumps(solid_metas, ensure_ascii=False, indent=2)
        + '\n'
    )
    META_TS.parent.mkdir(parents=True, exist_ok=True)
    META_TS.write_text(ts, encoding='utf-8')

    print(f'\n输出：')
    print(f'  骨架 PNG 数量: {len(skeleton_metas)}')
    print(f'  实心 polygon: {len(solid_metas)}')
    print(f'  PNG 目录: {OUT_DIR}')
    print(f'  TS 元数据: {META_TS}')


if __name__ == '__main__':
    main()
