// auto-generated by tools/scene-bbox/cutouts.py - do not edit
export type SceneCutout = {
  id: string
  src: string
  sceneX: number
  sceneY: number
  w: number
  h: number
  anchorY: number
}

export const SCENE_CUTOUTS: SceneCutout[] = [
  {
    "id": "upper_right_torii",
    "src": "/cutouts/upper_right_torii.png",
    "sceneX": 2937,
    "sceneY": 187,
    "w": 533,
    "h": 436,
    "anchorY": 615
  }
]
